// Settings module exports
export * from './validation';
export * from './settings-service';
export * from './settings-utils';

// Re-export settings-related types from the main types file
export type {
  UserSettings,
  ProfileSettings,
  NotificationSettings,
  DisplaySettings,
  PrivacySettings,
  AccountSettings,
  UserSetting,
  UserPreferences,
  UpdateProfileSettingsRequest,
  UpdateNotificationSettingsRequest,
  UpdateDisplaySettingsRequest,
  UpdatePrivacySettingsRequest,
  UpdateAccountSettingsRequest,
  ChangePasswordRequest,
  ChangeEmailRequest,
  SettingsResponse,
  UserSettingsResponse,
  ResetSettingsRequest,
  ExportUserDataResponse,
  SettingsContextType,
  SettingsPageProps,
  ProfileFormProps,
  NotificationFormProps,
  DisplayFormProps,
  PrivacyFormProps,
  AccountsFormProps,
  SettingsValidationError,
  SettingsValidationResult,
  SettingsEvent,
  UserSettingsAudit,
  SettingsCategory,
  ThemeOption,
  SyncFrequency,
  DateFormatOption,
  CurrencyOption,
  LanguageOption,
  TimezoneOption,
  DEFAULT_USER_PREFERENCES,
  THEME_OPTIONS,
  CURRENCY_OPTIONS,
  DATE_FORMAT_OPTIONS,
  LANGUAGE_OPTIONS,
  TIMEZONE_OPTIONS,
  SYNC_FREQUENCY_OPTIONS,
} from '../../types';